# -*- coding: utf-8 -*-
"""sum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/DEVINANDU/48c5aa027ed4b086c4cd6e7ffa2ba634/sum.ipynb
"""

a=10; b=20; c=a+b;
print(c)